# Generated by Django 3.2.7 on 2021-09-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('image_url', models.URLField(blank=True)),
                ('dish_components', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(max_length=40)),
                ('category', models.CharField(blank=True, choices=[('Bread', 'Bread'), ('Canape', 'Canape'), ('Cheese', 'Cheese'), ('Chips', 'Chips'), ('Core', 'Core'), ('Oil', 'Oils'), ('Pasta', 'Pasta'), ('Preservation', 'Preservation'), ('Starch', 'Starch'), ('Vegetable', 'Vegetable'), ('Technique', 'Technique'), ('First Course', 'First Course'), ('Meat', 'Meat'), ('Miscellaneous', 'Miscellaneous'), ('Stock', 'Stock')], default=None, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='recipe_db_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_of_measure', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_db_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='recipe_db_app.recipe')),
            ],
        ),
    ]
