# Generated by Django 3.2.7 on 2021-09-27 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebody',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
