# Generated by Django 3.2.7 on 2021-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db_app', '0003_alter_recipebody_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebody',
            name='dish_components',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
