# Generated by Django 3.2.7 on 2021-09-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db_app', '0004_alter_recipebody_dish_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
