# Generated by Django 3.2.7 on 2021-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db_app', '0009_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebody',
            name='image_url',
            field=models.URLField(default='https://drive.google.com/uc?export=view&id=1m1fHXCN-JA_4nNLdH5eeqStS-gAoFWNU', max_length=500),
        ),
    ]
