# Generated by Django 3.2.7 on 2021-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db_app', '0011_alter_recipebody_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
