# Generated by Django 3.2.7 on 2021-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db_app', '0012_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebody',
            name='dish_components',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
